### ISSUE TITLE
The Range -> Slice switch needs to be made here as well

### ISSUE THREAD

**Issue by ivorjawa** [tomstewart89/StateSpaceControl#1]
Search and replace of Range with Slice doesn't stop compilation errors.

In file included from /Users/kujawa/Projects/CatHouseStudio/photon_strip/Code/Apps/yoda/application.cpp:18:0:
/Users/kujawa/Projects/CatHouseStudio/photon_strip/Code/Apps/yoda/StateSpaceControl.h:44:58: error: wrong number of template arguments (1, should be 2)
         sys.Submatrix(Slice<outputs>(states),Slice<states>(0)) = outputMatrix;

In BasicLinearAlgebra.h:

// Represents a Slice of rows or columns used in the () operator to select a submatrix - I'll replace this with an iterator eventually
template<int start, int end> struct Slice { };

**Comment by tomstewart89** [comment]
Ahh so you're using this library too. I've made a PR to address this issue that you can find here: https://github.com/tomstewart89/StateSpaceControl/pull/2 I haven't had a chance to test it yet though so I'll do that on the weekend and merge it if it's all good. 

As a sidenote though, I'm planning on updating this library pretty drastically in the not too distant future (hopefully this weekend) so bear with me if there's some bugs here and there.

**Comment by ivorjawa** [comment]
In the state space initialize routine:

   // Find an inverse for the system matrix
        Matrix<states + inputs, states + outputs> sysInv = sys.Transpose() * (sys * sys.Transpose()).Inverse();
