### ISSUE TITLE
state feedback

### ISSUE THREAD

**Issue by KorgBoy** [tomstewart89/StateSpaceControl#5]
Hi there Tom. Nice work. Although, I don't quite understand your state feedback diagram. It's the one with the output 'y', which feeds back directly to 'x'. So the diagram is indicating that 'x' and 'y' are the same.

However, for a state-feedback diagram, the vector 'x' lies in a section before the output 'y'.
That is, 'x' is then applied to the matrix 'C', and the output of the 'C' block gives 'y'. That's how it should go, right? Thanks Tom.

**Comment by tomstewart89** [comment]
Hi Kenny,

Thanks for reading!

You're correct that the C matrix maps the state to an observation but for simplicity in that diagram we assume full state feedback (that magically we have access to the entire state in the observation 'y' such that C is the identity matrix). Obviously that's rarely the case so later on down the page the guide talks about how to introduce an estimator to recover an estimate for the state 'x_hat' given 'y'.

Hope that clears things up! Let me know if you have any further questions.
Tom

**Comment by KorgBoy** [comment]
Hi Tom! Thanks for explaining that! That really cleared up everything. That was my fault for not seeing that before! It looks like we might have to assume D = 0, which is pretty normal to do, so that 'x' is 'y'. Anyway, really nice work Tom. I'll definitely be trying out your code. Thanks for your time and those extra details about how to introduce an estimator for getting x_hat from y. Best regards. Kenny.

**Comment by tomstewart89** [comment]
No problem! I'm glad to hear you'll be trying out the code. I'm not sure how many people have used it besides me to date so if you have any trouble feel free to let me know!
