### ISSUE TITLE
constant gravity term in the state space model

### ISSUE THREAD

**Issue by Sriram510** [tomstewart89/StateSpaceControl#8]
Respected sir,

How can I deal with the constant gravity term with no state or input multiplied with it.

Regards,

sriram

**Comment by tomstewart89** [comment]
Hey @Sriram510, sorry for the slow reply, here. Thanks for your interest in my library! I'm not sure if the constant gravity term is in your observation function or in your dynamics but the following should work for either.

 If, for example, you have a constant term in your observation function then you can do one of two things:

1. Redefine your output variable as being the actual output minus your constant offset, ie: if `y = Cx + f` then instead use `y_bar = y - f` such that `y_bar = Cx`

2. Add a dummy variable to your state to represent the constant offset, i.e use `x_agg = [x,^T 1]^T` and `C_agg = [C, f]` such that the observation function becomes: `y = C_agg * x_agg`

Both of these approaches are described in slightly more detail in this [math stackexchange post](https://math.stackexchange.com/questions/2147263/state-space-model-with-constant-term-in-the-output-equation). Hope that helps!

**Comment by Sriram510** [comment]
Respected sir,

I have came to find that the gravity term can be added as the disturbance in the state transition matrix and let the integral control account for it. I was able to find the integral gain matrix using augmented matrices A,B,C and zeroes  and pole placemen t instead of Qlqr and Rlqr in matlab and then had run a simulation in arduino and several changes to your library file(w as noise in x_dot = Ax+Bu+w) and results were very accurate and the desired response was obtained successfully. Looking forward to contribute this project.
Thank you so much for the wonderful MIMO control library :)

Regards,
sriram swain

**Comment by tomstewart89** [comment]
Hi @Sriram510, that's great! I'm glad you managed to figure the problem out.

For posterity, do you think you could document your approach to finding the integral gain matrix over in #9? Also if you have any useful changes that you'd like to contribute feel free to open a PR!

I'm glad you got some use out of the library, good luck with your project!
